// lib/utils/pdf-export.ts
import jsPDF from 'jspdf'

interface HymnData {
  title: string
  lyrics: string
  language: string
  churchEvent?: string
  theme?: string
  composer?: string
}

export function generateHymnPDF(hymn: HymnData) {
  const doc = new jsPDF()
  
  let yPosition = 20
  const pageWidth = doc.internal.pageSize.getWidth()
  const pageHeight = doc.internal.pageSize.getHeight()
  const margin = 20
  const maxWidth = pageWidth - (2 * margin)

  // Title
  doc.setFontSize(24)
  doc.setFont('helvetica', 'bold')
  const titleLines = doc.splitTextToSize(hymn.title, maxWidth)
  doc.text(titleLines, pageWidth / 2, yPosition, { align: 'center' })
  yPosition += titleLines.length * 10 + 10

  // Metadata
  doc.setFontSize(10)
  doc.setFont('helvetica', 'normal')
  
  const metadata = []
  if (hymn.language) metadata.push(`Language: ${hymn.language}`)
  if (hymn.churchEvent) metadata.push(`Event: ${hymn.churchEvent}`)
  if (hymn.theme) metadata.push(`Theme: ${hymn.theme}`)
  
  if (metadata.length > 0) {
    doc.text(metadata.join(' • '), pageWidth / 2, yPosition, { align: 'center' })
    yPosition += 15
  }

  // Separator line
  doc.setLineWidth(0.5)
  doc.line(margin, yPosition, pageWidth - margin, yPosition)
  yPosition += 10

  // Lyrics
  doc.setFontSize(12)
  doc.setFont('times', 'normal')
  
  const verses = hymn.lyrics.split('\n\n')
  
  verses.forEach((verse, index) => {
    // Check if we need a new page
    if (yPosition > pageHeight - 40) {
      doc.addPage()
      yPosition = 20
    }

    const verseLines = verse.split('\n')
    verseLines.forEach((line) => {
      if (line.trim()) {
        const wrappedLines = doc.splitTextToSize(line, maxWidth)
        wrappedLines.forEach((wrappedLine: string) => {
          doc.text(wrappedLine, margin, yPosition)
          yPosition += 7
        })
      } else {
        yPosition += 7
      }
    })
    
    // Space between verses
    yPosition += 10
  })

  // Footer
  doc.setFontSize(8)
  doc.setFont('helvetica', 'italic')
  const footer = 'Generated by FaithBeat - AI Hymn Composer'
  doc.text(footer, pageWidth / 2, pageHeight - 10, { align: 'center' })

  return doc
}

export function downloadHymnPDF(hymn: HymnData) {
  const doc = generateHymnPDF(hymn)
  const filename = `${hymn.title.replace(/[^a-z0-9]/gi, '_').toLowerCase()}.pdf`
  doc.save(filename)
}

export function printHymnPDF(hymn: HymnData) {
  const doc = generateHymnPDF(hymn)
  doc.autoPrint()
  window.open(doc.output('bloburl'), '_blank')
}