// lib/utils/sheet-music-export.ts
import jsPDF from 'jspdf'
import html2canvas from 'html2canvas'

interface SheetMusicData {
  title: string
  language: string
  theme?: string
  musicXml?: string
  voices: {
    part: 'soprano' | 'alto' | 'tenor' | 'bass'
    notation: string
  }[]
  keySignature?: string
  timeSignature?: string
  tempoBpm?: number
}

/**
 * Generate sheet music PDF from SATB arrangement data
 */
export async function generateSheetMusicPDF(data: SheetMusicData) {
  const doc = new jsPDF({
    orientation: 'portrait',
    unit: 'mm',
    format: 'a4'
  })

  const pageWidth = doc.internal.pageSize.getWidth()
  const pageHeight = doc.internal.pageSize.getHeight()
  const margin = 15
  let yPosition = margin

  // Title
  doc.setFontSize(20)
  doc.setFont('helvetica', 'bold')
  doc.text(data.title, pageWidth / 2, yPosition, { align: 'center' })
  yPosition += 15

  // Metadata
  doc.setFontSize(10)
  doc.setFont('helvetica', 'normal')
  const metadata = []
  if (data.keySignature) metadata.push(`Key: ${data.keySignature}`)
  if (data.timeSignature) metadata.push(`Time: ${data.timeSignature}`)
  if (data.tempoBpm) metadata.push(`Tempo: ${data.tempoBpm} BPM`)
  
  if (metadata.length > 0) {
    doc.text(metadata.join(' • '), pageWidth / 2, yPosition, { align: 'center' })
    yPosition += 10
  }

  // Add spacing
  yPosition += 5

  // Voice parts (Soprano, Alto, Tenor, Bass)
  doc.setFontSize(11)
  doc.setFont('helvetica', 'bold')
  
  data.voices.forEach((voice) => {
    if (yPosition > pageHeight - 30) {
      doc.addPage()
      yPosition = margin
    }

    // Voice part label
    doc.setFont('helvetica', 'bold')
    doc.setFontSize(11)
    doc.text(`${voice.part.toUpperCase()}:`, margin, yPosition)
    yPosition += 8

    // Notation/lyrics
    doc.setFont('courier', 'normal')
    doc.setFontSize(9)
    const lines = doc.splitTextToSize(voice.notation, pageWidth - 2 * margin)
    lines.forEach((line: string) => {
      if (yPosition > pageHeight - 20) {
        doc.addPage()
        yPosition = margin
      }
      doc.text(line, margin + 5, yPosition)
      yPosition += 6
    })

    yPosition += 5
  })

  // Footer
  doc.setFontSize(8)
  doc.setFont('helvetica', 'italic')
  const footer = 'Generated by FaithBeat - AI Hymn Composer'
  doc.text(footer, pageWidth / 2, pageHeight - 10, { align: 'center' })

  return doc
}

export function downloadSheetMusicPDF(data: SheetMusicData) {
  generateSheetMusicPDF(data).then((doc) => {
    const filename = `${data.title.replace(/[^a-z0-9]/gi, '_').toLowerCase()}_sheet_music.pdf`
    doc.save(filename)
  })
}

export function printSheetMusic(data: SheetMusicData) {
  generateSheetMusicPDF(data).then((doc) => {
    doc.autoPrint()
    window.open(doc.output('bloburl'), '_blank')
  })
}

/**
 * Alternative: Render sheet music using HTML canvas and convert to PDF
 * Useful if you're generating visual sheet music with notation libraries
 */
export async function exportSheetMusicFromCanvas(
  canvasElement: HTMLCanvasElement,
  title: string
) {
  const doc = new jsPDF({
    orientation: 'landscape',
    unit: 'mm',
    format: 'a4'
  })

  const image = canvasElement.toDataURL('image/png')
  const pageWidth = doc.internal.pageSize.getWidth()
  const pageHeight = doc.internal.pageSize.getHeight()

  doc.addImage(image, 'PNG', 0, 0, pageWidth, pageHeight)
  doc.save(`${title}_sheet_music.pdf`)
}
