// lib/utils/vexflow-sheet-music.ts
import jsPDF from 'jspdf'

/**
 * Advanced sheet music generation using canvas rendering
 * This creates a more professional PDF with musical notation
 */

interface VoicePart {
  part: 'soprano' | 'alto' | 'tenor' | 'bass'
  notation: string
}

interface SheetMusicConfig {
  title: string
  keySignature: string
  timeSignature: string
  tempoBpm: number
  voices: VoicePart[]
  composer?: string
}

/**
 * Creates a simple staff line for visual representation
 * Use this if you're using canvas to render the sheet music
 */
export function createStaffCanvas(width: number = 800, height: number = 200): HTMLCanvasElement {
  const canvas = document.createElement('canvas')
  canvas.width = width
  canvas.height = height
  
  const ctx = canvas.getContext('2d')!
  ctx.strokeStyle = '#000'
  ctx.lineWidth = 1
  
  // Draw 5 staff lines
  const lineSpacing = 20
  const topMargin = 40
  
  for (let i = 0; i < 5; i++) {
    const y = topMargin + i * lineSpacing
    ctx.beginPath()
    ctx.moveTo(40, y)
    ctx.lineTo(width - 40, y)
    ctx.stroke()
  }
  
  // Draw clef placeholder (treble clef)
  ctx.font = 'bold 40px serif'
  ctx.fillText('𝄞', 50, topMargin + 40)
  
  return canvas
}

/**
 * Generate professional sheet music PDF with MusicXML or text notation
 */
export function generateProfessionalSheetMusicPDF(config: SheetMusicConfig): jsPDF {
  const doc = new jsPDF({
    orientation: 'portrait',
    unit: 'mm',
    format: 'a4'
  })

  const pageWidth = doc.internal.pageSize.getWidth()
  const pageHeight = doc.internal.pageSize.getHeight()
  const margin = 15
  let yPosition = margin

  // Title
  doc.setFontSize(24)
  doc.setFont('helvetica', 'bold')
  doc.text(config.title, pageWidth / 2, yPosition, { align: 'center' })
  yPosition += 15

  // Musical Information
  doc.setFontSize(10)
  doc.setFont('helvetica', 'normal')
  
  const musicInfo = []
  if (config.keySignature) musicInfo.push(`Key: ${config.keySignature}`)
  if (config.timeSignature) musicInfo.push(`Time: ${config.timeSignature}`)
  if (config.tempoBpm) musicInfo.push(`Tempo: ${config.tempoBpm} BPM`)
  
  if (musicInfo.length > 0) {
    doc.text(musicInfo.join(' • '), pageWidth / 2, yPosition, { align: 'center' })
  }
  
  yPosition += 12

  // Separator
  doc.setLineWidth(0.5)
  doc.line(margin, yPosition, pageWidth - margin, yPosition)
  yPosition += 10

  // Voice parts with formatting
  config.voices.forEach((voice, voiceIndex) => {
    // Move to new page if needed
    if (yPosition > pageHeight - 40) {
      doc.addPage()
      yPosition = margin
    }

    // Voice label with background color
    const voiceColors: Record<string, [number, number, number]> = {
      soprano: [230, 200, 240], // pink
      alto: [200, 230, 240],     // light blue
      tenor: [240, 230, 200],    // light orange
      bass: [200, 240, 230]      // light green
    }

    const bgColor = voiceColors[voice.part] || [240, 240, 240]
    doc.setFillColor(bgColor[0], bgColor[1], bgColor[2])
    doc.rect(margin - 5, yPosition - 5, pageWidth - 2 * margin + 10, 8, 'F')

    doc.setFontSize(12)
    doc.setFont('helvetica', 'bold')
    doc.setTextColor(0, 0, 0)
    doc.text(`${voice.part.toUpperCase()}`, margin, yPosition + 1)
    
    yPosition += 10

    // Notation lines
    doc.setFontSize(9)
    doc.setFont('courier', 'normal')
    const notationLines = doc.splitTextToSize(voice.notation, pageWidth - 2 * margin - 10)
    
    notationLines.forEach((line: string) => {
      if (yPosition > pageHeight - 20) {
        doc.addPage()
        yPosition = margin
      }
      
      doc.text(line, margin + 5, yPosition)
      yPosition += 6
    })

    yPosition += 8
  })

  // Footer with metadata
  yPosition = pageHeight - 10
  doc.setFontSize(8)
  doc.setFont('helvetica', 'italic')
  doc.setTextColor(100, 100, 100)
  doc.text('Generated by FaithBeat - AI Hymn Composer', pageWidth / 2, yPosition, { align: 'center' })

  return doc
}

export function downloadProfessionalSheetMusic(config: SheetMusicConfig) {
  const doc = generateProfessionalSheetMusicPDF(config)
  const filename = `${config.title.replace(/[^a-z0-9]/gi, '_').toLowerCase()}_score.pdf`
  doc.save(filename)
}

export function printProfessionalSheetMusic(config: SheetMusicConfig) {
  const doc = generateProfessionalSheetMusicPDF(config)
  doc.autoPrint()
  window.open(doc.output('bloburl'), '_blank')
}
